### ISSUE TITLE
DESIGN

### ISSUE THREAD

**Issue by lundgren98** [lundgren98/Zoo#3]
Creation of a DESIGN.md file is needed.
Contributors should write or copy some bullet points from Lesson 4 that describes the desired features, including nouns and verbs used. Also add the diagram as an image or similar.

**Comment by Telf92** [comment]
We need a Mermaid.

**Comment by PapaPeskwo** [comment]
Jättebra

**Comment by PapaPeskwo** [comment]
Behöver relationer, och bättre utsende/format

**Comment by Telf92** [comment]
Looks awesome right now.
