### ISSUE TITLE
Tester Personal

### ISSUE THREAD

**Issue by PapaPeskwo** [lundgren98/Zoo#7]
## Sälja
- Biljett
    - 1 såld biljett = Personal salary + int 

## Feed
- call Feed.animal()
    - true(djuret ska äta)/false(djuret ska icke äta) 

## Clean
- call Enclosure.clean()
   - True = behöver städas
   - False = behöver inte städas

## Accept Payment
- Saldo += Salary

**Comment by lundgren98** [comment]
More tests needed.

**Comment by PapaPeskwo** [comment]
## Förbättrade tester | 3 st | Alexander & Tomislav
sellTicket blir två:
- sellTicketAccepted
- sellTicketDeclined
Två nya tester för att tvätta djuren
- washDirtyAnimal
- washCleanAnimal

**Comment by lundgren98** [comment]
make green plox
