### ISSUE TITLE
Total 20 test cases

### ISSUE THREAD

**Issue by PapaPeskwo** [lundgren98/Zoo#9]
- At least a total of 20 test cases and none of them failing

**Comment by PapaPeskwo** [comment]
## Enclosure Test | 6 tester
- testGetSize
- testGetDirty
- testGetTemperature
- testClean
- testClose
- testOpen

## Lemur Test | 6 Tester
- shouldEat
- shouldSleep
- shouldSnuggle
- shouldSpeak
- shouldBackflip
- shoudBliÄldre

## Personell Test | 6 Tester
- sellTicket
- feedHungryAnimal
- feedFullAnimal
- cleanDirtyEnclosure
- cleanCleanEnclosure
- acceptPayment

### Totalt 18 tester as of 15/01/2023, behöver 2 till :^)

**Comment by lundgren98** [comment]
Aight. Får la kolla igenom designen, se om ngt saknas.
I värsta fall om inget saknas får man hitta på något själv.

**Comment by PapaPeskwo** [comment]
Ja, vi kan ju fixa d imorgon

**Comment by lundgren98** [comment]
We are done! :D
